spring:
  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oj?serverTimezone=Asia/Shanghai
    username: root
    password: '@Qwdsrs020216'
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
    password: 123456
cos:
  client:
    accessKeyId: LTAI5tBVZXjh4dbA1LFDW7me
    accessKeySecret: iz5v96aqWIjuEtUcFEDMXaTSbyniCv
    endpoint: https://oss-cn-chengdu.aliyuncs.com
    bucketName: my-oj